apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: parking
  template:
    metadata:
      labels:
        app.kubernetes.io/name: parking
    spec:
      containers:
        - name: parking
          # Using local image for demonstration
          image: parking:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          # Command to run against entrypoint
          #args: ["start"]
          env:
            - name: PORT
              value: "8000"
            - name: SECRET_KEY_BASE
              value: "not-a-secret"
            - name: RELEASE_COOKIE
              value: "monster"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
